### PR TITLE
Factoring vectors.S

### PR DESCRIPTION
**Pull request by edogaldo**
Hi Nick, I'd propose you this PR in order to factor the vectors.S file avoiding duplications.

What about it?

Best, E.

### CODE REVIEW

**Comment by edogaldo** [comment]
Hi Nick, I made a further change redefining the reset handler and making it call main().
This way the application code seams me neater.

Hope this helps.

Best, E.

**Comment by spbnick** [comment]
Hi Edoardo, thanks for the pull request! I'll take a closer look at it on the weekend.

**Comment by spbnick** [comment]
This looks good in general. I wanted to deal with those vectors for a while, but lacked good knowledge and time to do it. Thanks a lot! I feel I can learn more about the assembler from you :)

However, I'd like to do it slightly differently, use macros, and also avoid unnecessary whitespace changes in the process.

One thing about renaming `reset_handler` to `main` is that the code in `main` is generally expected to be ready to run and have all the setup done. However, it's not the case with the current code. For example, global initialized variables are not copied to memory from flash. I'll do the rename, but I would welcome a contribution of some more init code to go into the `reset_handler` ;)

**Comment by edogaldo** [comment]
Hi Nick, glad you appreciated.
In truth I didn't invent anything, I just took inspiration from ST's Standard Peripheral Library initialization files taking the very minimum changes in order to avoid upsetting your approach which I liked for its essentiality. Anyway there you can find also further initialization code for global variables if you want to add it in the reset handler.
Personally I like the approach of having almost everything (including the initialization code) under control within the main function.
I'd also suggest you this library which provides an alternative approach for defining the vectors table and the initialization code in the form of C file: https://github.com/geoffreymbrown/STM32-Template

Best regards, E.

**Pull request closed without merging**
